<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('materials')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('materials')->insert([
        [
            'code'             => 'MAT-001',
            'name'             => 'ARM, STAY FENDER 1 & 2',
            'part_name'        => 'ARM, STAY FENDER 1 & 2',
            'part_no'          => '2PV-F1585-00',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø15.9 x Ø1.6 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'SPINDO',
            'panjang_material' => 3100.0,
            'panjang_part'     => 47.6,
            'bq'               => 61.2648,
            'current_stock'    => 1000.0,
            'minimum_stock'    => 500.0,
            'max_stock'        => 1500.0,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-002',
            'name'             => 'AS JOINT SHROUD',
            'part_name'        => 'AS JOINT SHROUD',
            'part_no'          => '19040-K84-9001-21',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø8 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => 3000.0,
            'panjang_part'     => 289.6,
            'bq'               => 10.2529,
            'current_stock'    => 1500.0,
            'minimum_stock'    => 1500.0,
            'max_stock'        => 3000.0,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-003',
            'name'             => 'BAR COMP STD STOPPER',
            'part_name'        => 'BAR COMP STD STOPPER',
            'part_no'          => '50196-KWWX-6003-HI',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø14 x 150',
            'unit'             => 'pcs',
            'supplier'         => 'MPP',
            'panjang_material' => 150.0,
            'panjang_part'     => 150.0,
            'bq'               => 0.9804,
            'current_stock'    => 500.0,
            'minimum_stock'    => 1000.0,
            'max_stock'        => 5000.0,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-004',
            'name'             => 'BAR CROSS',
            'part_name'        => 'BAR CROSS',
            'part_no'          => '2PV-XFI41-00',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø16 x 150',
            'unit'             => 'pcs',
            'supplier'         => 'MPP',
            'panjang_material' => 156.5,
            'panjang_part'     => 156.5,
            'bq'               => 0.9812,
            'current_stock'    => 3000.0,
            'minimum_stock'    => 1000.0,
            'max_stock'        => 3000.0,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-005',
            'name'             => 'BAR INNER K45',
            'part_name'        => 'BAR INNER K45',
            'part_no'          => '50530-K45-N000-21',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø17.3  x Ø2 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'ISTW',
            'panjang_material' => 3000.0,
            'panjang_part'     => 30.0,
            'bq'               => 90.9091,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-006',
            'name'             => 'BAR STAND K64J',
            'part_name'        => 'BAR STAND K64J',
            'part_no'          => '50530-K64 -NA00-20',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø25/17.2  x Ø2 x 245',
            'unit'             => 'pcs',
            'supplier'         => 'BME',
            'panjang_material' => 188.5,
            'panjang_part'     => 188.5,
            'bq'               => 0.9843,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-007',
            'name'             => 'BAR STAND K64A',
            'part_name'        => 'BAR STAND K64A',
            'part_no'          => '50530-K64 -N000-20',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø25/17.2  x Ø2 x 245',
            'unit'             => 'pcs',
            'supplier'         => 'BME',
            'panjang_material' => 188.5,
            'panjang_part'     => 188.5,
            'bq'               => 0.9843,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-008',
            'name'             => 'BOSS K64A',
            'part_name'        => 'BOSS K64A',
            'part_no'          => '46500-K64A-N000-22',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø22.2 x Ø14.5 x 3300',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 3350.0,
            'panjang_part'     => 18.5,
            'bq'               => 155.814,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-009',
            'name'             => 'Boss Main Stand 1',
            'part_name'        => 'Boss Main Stand 1',
            'part_no'          => '1FD-F1437-00',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø20 x Ø15.2 x 2400',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 2000.0,
            'panjang_part'     => 7.8,
            'bq'               => 185.1852,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-010',
            'name'             => 'Boss Main Stand 2',
            'part_name'        => 'Boss Main Stand 2',
            'part_no'          => '1FD-F138-00',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø20 x Ø15.2 x 2400',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 2000.0,
            'panjang_part'     => 12.8,
            'bq'               => 126.5823,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-011',
            'name'             => 'Collar 87A1',
            'part_name'        => 'Collar 87A1',
            'part_no'          => '90387-064W3',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø9.4 x Ø1.5 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'TOP TUBE',
            'panjang_material' => 3000.0,
            'panjang_part'     => 13.0,
            'bq'               => 187.5,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-012',
            'name'             => 'COLLAR ABSORBER',
            'part_name'        => 'COLLAR ABSORBER',
            'part_no'          => '48516-25050-A',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø24 x Ø18 x 2000',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 2000.0,
            'panjang_part'     => 51.2,
            'bq'               => 36.9004,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-013',
            'name'             => 'COLLAR K64J',
            'part_name'        => 'COLLAR K64J',
            'part_no'          => '24711-K64J-ND00-22',
            'customer'         => 'PT.BME',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-014',
            'name'             => 'COLLAR KOJA',
            'part_name'        => 'COLLAR KOJA',
            'part_no'          => '50500-KOJA-N002-22',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø15 x Ø10.1 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 6000.0,
            'panjang_part'     => 126.0,
            'bq'               => 46.5116,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-015',
            'name'             => 'COLLAR RR BRAKE PIVOT',
            'part_name'        => 'COLLAR RR BRAKE PIVOT',
            'part_no'          => '50190-KWW0-6000-23',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø25.4 x Ø3.1 x 1000',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 1000.0,
            'panjang_part'     => 8.0,
            'bq'               => 90.9091,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-016',
            'name'             => 'COLLAR SHAFT, PULLER CHAIN 5BP',
            'part_name'        => 'COLLAR SHAFT, PULLER CHAIN 5BP',
            'part_no'          => '5BP-F5388-00',
            'customer'         => 'PT.BME',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-017',
            'name'             => 'PEDAL K64A',
            'part_name'        => 'PEDAL K64A',
            'part_no'          => '46500-K64A-N000-22',
            'customer'         => 'PT. BME',
            'specification'    => 'Ø17,3 x Ø2,3 x 250',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 250.0,
            'panjang_part'     => 51.0,
            'bq'               => 4.6296,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-018',
            'name'             => 'Pin Hook K41',
            'part_name'        => 'Pin Hook K41',
            'part_no'          => '50610-KYZ-9000-27',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø8 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => 3000.0,
            'panjang_part'     => 38.0,
            'bq'               => 73.1707,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-019',
            'name'             => 'Pin K1AA',
            'part_name'        => 'Pin K1AA',
            'part_no'          => '50503-KZL-9300-22',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø8 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => 3000.0,
            'panjang_part'     => 28.0,
            'bq'               => 96.7742,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-020',
            'name'             => 'Pin Spring hook KPH',
            'part_name'        => 'Pin Spring hook KPH',
            'part_no'          => '50259-KPH-9000-H1',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø8 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => 3000.0,
            'panjang_part'     => 17.5,
            'bq'               => 146.3415,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-021',
            'name'             => 'Pipa Rod OTL',
            'part_name'        => 'Pipa Rod OTL',
            'part_no'          => '841',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø50.8 x Ø2 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'BME',
            'panjang_material' => 3000.0,
            'panjang_part'     => 320.0,
            'bq'               => 9.2879,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-022',
            'name'             => 'Pipe  3',
            'part_name'        => 'Pipe  3',
            'part_no'          => '2PV-XF141-00-C',
            'customer'         => 'PT.BME',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-023',
            'name'             => 'Pipe main Stand Pivot',
            'part_name'        => 'Pipe main Stand Pivot',
            'part_no'          => '50512-KAN-9610-A',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø16.8 x Ø12.1 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 6000.0,
            'panjang_part'     => 122.0,
            'bq'               => 48.0,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-024',
            'name'             => 'Pipe Stand Inner k81',
            'part_name'        => 'Pipe Stand Inner k81',
            'part_no'          => '50530-K81A-N001-21',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø15.9 x Ø1.4 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'SPINDO',
            'panjang_material' => 3000.0,
            'panjang_part'     => 31.0,
            'bq'               => 88.2353,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-025',
            'name'             => 'Pipe Stand Pivot',
            'part_name'        => 'Pipe Stand Pivot',
            'part_no'          => '50107-K56A-N0006-21',
            'customer'         => 'PT.BME',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-026',
            'name'             => 'Pipe Link Eng Hanger',
            'part_name'        => 'Pipe Link Eng Hanger',
            'part_no'          => '50351-K0J -N000-28',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø10.8 x Ø17.3 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 6200.0,
            'panjang_part'     => 126.6,
            'bq'               => 47.8395,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-027',
            'name'             => 'Pivot Stand Pipe',
            'part_name'        => 'Pivot Stand Pipe',
            'part_no'          => '50500-K15-9200-21',
            'customer'         => 'PT.BME',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => 6000.0,
            'panjang_part'     => 20.0,
            'bq'               => 260.8696,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-028',
            'name'             => 'Shaft Koja',
            'part_name'        => 'Shaft Koja',
            'part_no'          => '50503-KOJA-N003-20',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø9.95 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => 6000.0,
            'panjang_part'     => 184.0,
            'bq'               => 32.0856,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-029',
            'name'             => 'Shaft Main Stand Pivot',
            'part_name'        => 'Shaft Main Stand Pivot',
            'part_no'          => '50526-KVX-6000-A',
            'customer'         => 'PT.BME',
            'specification'    => 'Ø16.8 x Ø12 x 5500',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 5500.0,
            'panjang_part'     => 202.5,
            'bq'               => 26.764,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-030',
            'name'             => 'Spring Seatlock',
            'part_name'        => 'Spring Seatlock',
            'part_no'          => '77234-KYZ-9000',
            'customer'         => 'PT.BME',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-031',
            'name'             => 'Bar Eng Stopper',
            'part_name'        => 'Bar Eng Stopper',
            'part_no'          => '50351-K59-A100-33',
            'customer'         => 'PT.BME P3',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-032',
            'name'             => 'Collar K2VM/ K2sa',
            'part_name'        => 'Collar K2VM/ K2sa',
            'part_no'          => '50500-K59 -A100-24',
            'customer'         => 'PT.BME P3',
            'specification'    => 'Ø15 x Ø10.1 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 2550.0,
            'panjang_part'     => 134.0,
            'bq'               => 18.6131,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-033',
            'name'             => 'Collar KZR/K59',
            'part_name'        => 'Collar KZR/K59',
            'part_no'          => '50351-KZR-6000-21',
            'customer'         => 'PT.BME P3',
            'specification'    => 'Ø15 x Ø10.1 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 2550.0,
            'panjang_part'     => 175.5,
            'bq'               => 14.2857,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-034',
            'name'             => 'Pipe Link K0J',
            'part_name'        => 'Pipe Link K0J',
            'part_no'          => '50351-K0J -N000-28',
            'customer'         => 'PT.BME P3',
            'specification'    => 'Ø10.8 x Ø17.3 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 6200.0,
            'panjang_part'     => 126.6,
            'bq'               => 47.8395,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-035',
            'name'             => 'BOSS K64A',
            'part_name'        => 'BOSS K64A',
            'part_no'          => '46500-K64A-N000-22',
            'customer'         => 'PT. CPL',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-036',
            'name'             => 'PEDAL K64A',
            'part_name'        => 'PEDAL K64A',
            'part_no'          => '46500-K64A-N000-22',
            'customer'         => 'PT. CPL',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-037',
            'name'             => 'Collar KOJJ',
            'part_name'        => 'Collar KOJJ',
            'part_no'          => '50500-KOJA-N002-22',
            'customer'         => 'PT. INDTA',
            'specification'    => 'Ø15 x Ø10.1 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 6000.0,
            'panjang_part'     => 126.0,
            'bq'               => 46.5116,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-038',
            'name'             => 'Boss Brake Pedal',
            'part_name'        => 'Boss Brake Pedal',
            'part_no'          => '43122-09G00',
            'customer'         => 'PT. STALLION',
            'specification'    => 'Ø25.4  x Ø11.8 x 3800',
            'unit'             => 'pcs',
            'supplier'         => 'SSI',
            'panjang_material' => 3800.0,
            'panjang_part'     => 36.0,
            'bq'               => 97.4359,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-039',
            'name'             => 'Bolt Lurus',
            'part_name'        => 'Bolt Lurus',
            'part_no'          => 'SZ106-08029',
            'customer'         => 'PT. YK',
            'specification'    => 'Ø12  x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'MSD',
            'panjang_material' => NULL,
            'panjang_part'     => 34.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-040',
            'name'             => 'Bolt Tirus',
            'part_name'        => 'Bolt Tirus',
            'part_no'          => 'SZ106-08030',
            'customer'         => 'PT. YK',
            'specification'    => 'Ø14  x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'MSD',
            'panjang_material' => NULL,
            'panjang_part'     => 38.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-041',
            'name'             => 'Collar Bumper',
            'part_name'        => 'Collar Bumper',
            'part_no'          => '52525-EWO21',
            'customer'         => 'PT. YK',
            'specification'    => 'Ø25.4 x Ø3.1 x 1000',
            'unit'             => 'pcs',
            'supplier'         => 'SPS',
            'panjang_material' => 1000.0,
            'panjang_part'     => 5.9,
            'bq'               => 112.3596,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-042',
            'name'             => 'PIN HINGE',
            'part_name'        => 'PIN HINGE',
            'part_no'          => 'MC908212',
            'customer'         => 'PT.GDM',
            'specification'    => 'Ø14 x 6000',
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => 76.0,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-043',
            'name'             => 'PIN 1PA',
            'part_name'        => 'PIN 1PA',
            'part_no'          => '1PA - F4374 00',
            'customer'         => 'PT.GDM',
            'specification'    => 'Ø8.95 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => NULL,
            'panjang_part'     => 60.0,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-044',
            'name'             => 'BAR CROSS TUBE',
            'part_name'        => 'BAR CROSS TUBE',
            'part_no'          => '5D9-F1413-00',
            'customer'         => 'PT.GDM',
            'specification'    => 'Ø16 x 150',
            'unit'             => 'pcs',
            'supplier'         => 'MPP',
            'panjang_material' => NULL,
            'panjang_part'     => 156.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-045',
            'name'             => 'LOCK SPARE WHEEL',
            'part_name'        => 'LOCK SPARE WHEEL',
            'part_no'          => '51938-VT010',
            'customer'         => 'PT.GDM',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => 'GDM',
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => 1.0,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-046',
            'name'             => 'PIPE HEAD BWP',
            'part_name'        => 'PIPE HEAD BWP',
            'part_no'          => 'BWP',
            'customer'         => 'PT.GDM',
            'specification'    => 'Ø17.4 x Ø11.25 x 3600',
            'unit'             => 'pcs',
            'supplier'         => 'GDM',
            'panjang_material' => 3200.0,
            'panjang_part'     => 122.5,
            'bq'               => 25.498,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-047',
            'name'             => 'TUBE BAR CROSS 1DY',
            'part_name'        => 'TUBE BAR CROSS 1DY',
            'part_no'          => '-',
            'customer'         => 'PT.GDM',
            'specification'    => 'Ø22.2 x Ø2.8 x 3090',
            'unit'             => 'pcs',
            'supplier'         => 'GDM',
            'panjang_material' => 3090.0,
            'panjang_part'     => 129.0,
            'bq'               => 23.4091,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-048',
            'name'             => 'PIPE CONNECTING BWN',
            'part_name'        => 'PIPE CONNECTING BWN',
            'part_no'          => 'BWN-F4112-00',
            'customer'         => 'PT.GDM',
            'specification'    => 'Ø6.5 x Ø1.2 x 3000',
            'unit'             => 'pcs',
            'supplier'         => 'GDM',
            'panjang_material' => 3000.0,
            'panjang_part'     => 51.0,
            'bq'               => 55.5556,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-049',
            'name'             => 'NUT HEIGHT ROUND',
            'part_name'        => 'NUT HEIGHT ROUND',
            'part_no'          => '9004A-17141',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø16 x 20',
            'unit'             => 'pcs',
            'supplier'         => 'MPP',
            'panjang_material' => 20.0,
            'panjang_part'     => 20.0,
            'bq'               => 0.8696,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-050',
            'name'             => 'BOLT ADJUSTER CAB LOCK ROD',
            'part_name'        => 'BOLT ADJUSTER CAB LOCK ROD',
            'part_no'          => '97588026004',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø11 x 6000',
            'unit'             => 'pcs',
            'supplier'         => 'MZ',
            'panjang_material' => NULL,
            'panjang_part'     => 60.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-051',
            'name'             => 'BOSS 1FD',
            'part_name'        => 'BOSS 1FD',
            'part_no'          => '1FD-F612F-00',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø16 x 34',
            'unit'             => 'pcs',
            'supplier'         => 'MPP',
            'panjang_material' => 34.0,
            'panjang_part'     => 34.0,
            'bq'               => 0.9189,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-052',
            'name'             => 'ROD SHIFT BBS',
            'part_name'        => 'ROD SHIFT BBS',
            'part_no'          => 'BBS-E8115-00',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø6 x 3000',
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => 263.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-053',
            'name'             => 'ROD SHIFT BDJ',
            'part_name'        => 'ROD SHIFT BDJ',
            'part_no'          => 'BDJ-E8115-00',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø6 x 3000',
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => 163.1,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-054',
            'name'             => 'ROD SHIFT 3C1',
            'part_name'        => 'ROD SHIFT 3C1',
            'part_no'          => '3C1-E9115-00',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø6 x 3000',
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => 163.1,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-055',
            'name'             => 'ROD SHIFT 1WD',
            'part_name'        => 'ROD SHIFT 1WD',
            'part_no'          => '1WD-E8115-00',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø5 x 3000',
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => 116.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-056',
            'name'             => 'SPACER B3F',
            'part_name'        => 'SPACER B3F',
            'part_no'          => 'B3F',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø17.5 x Ø11.1 x 3300',
            'unit'             => 'pcs',
            'supplier'         => 'SGS',
            'panjang_material' => 3000.0,
            'panjang_part'     => 123.0,
            'bq'               => 23.8095,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-057',
            'name'             => 'ROD SHIFT 2PK',
            'part_name'        => 'ROD SHIFT 2PK',
            'part_no'          => '2PKE811500080',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø6 x 3000',
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => 247.5,
            'bq'               => NULL,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-058',
            'name'             => 'CROSS TUBE 2',
            'part_name'        => 'CROSS TUBE 2',
            'part_no'          => 'B3M-F1197-00',
            'customer'         => 'PT. SGS',
            'specification'    => NULL,
            'unit'             => 'pcs',
            'supplier'         => NULL,
            'panjang_material' => NULL,
            'panjang_part'     => NULL,
            'bq'               => 1.0,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        [
            'code'             => 'MAT-059',
            'name'             => 'BOSS 1WD',
            'part_name'        => 'BOSS 1WD',
            'part_no'          => '145P-E818A-00',
            'customer'         => 'PT. SGS',
            'specification'    => 'Ø20 x Ø14.1 x 2800',
            'unit'             => 'pcs',
            'supplier'         => 'SGS',
            'panjang_material' => 2900.0,
            'panjang_part'     => 22.0,
            'bq'               => 116.0,
            'current_stock'    => 0,
            'minimum_stock'    => 0,
            'max_stock'        => NULL,
            'is_active'        => true,
            'created_at'       => now(),
            'updated_at'       => now(),
        ],
        ]);
    }
}